version: 2.1

orbs:
  node: circleci/node@7.1.1

executors:
  node:
    docker:
      - image: cimg/node:22.19.0

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context:
            - npm-readonly
      - test:
          context:
            - npm-readonly
      - publish:
          context:
            - npm-publish
            - github
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - main

commands:
  bootstrap:
    steps:
      - checkout
      - run: 'echo "npmAuthToken: $NPM_TOKEN" >> ${HOME}/.yarnrc.yml'
      - node/install-packages:
          pkg-manager: yarn-berry
          with-cache: true
          include-branch-in-cache-key: false

jobs:
  build:
    executor: node
    working_directory: ~/project
    steps:
      - bootstrap
      - run: yarn build

  test:
    executor: node
    working_directory: ~/project
    steps:
      - bootstrap
      - run: yarn test

  publish:
    executor: node
    working_directory: ~/project
    steps:
      - bootstrap
      - run: yarn build
      - run: ./bump.sh package.json
      - run: yarn npm publish
